# Generated by Django 4.2.5 on 2023-09-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('man_name1', models.CharField(max_length=30)),
                ('med_name1', models.CharField(max_length=30)),
                ('dosage1', models.CharField(max_length=30)),
                ('type1', models.CharField(max_length=30)),
                ('qty1', models.IntegerField()),
                ('price1', models.IntegerField()),
                ('mtf1', models.CharField(max_length=30)),
                ('med_pic1', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('est_del_date', models.DateField(null=True)),
                ('products', models.CharField(max_length=200)),
                ('prod_img', models.FileField(upload_to='')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.CharField(max_length=30)),
                ('med_name', models.CharField(max_length=30)),
                ('dosage', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('baby', 'Baby Care'), ('health', 'Health and Drink Suppliments'), ('women', 'Women Care'), ('personal', 'Personal Care'), ('ayurveda', 'ayurveda'), ('healthd', 'Health Devices'), ('home', 'Home Essentials'), ('healthc', 'Health Condition')], max_length=30)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('mtf', models.CharField(max_length=30)),
                ('med_pic', models.FileField(upload_to='ecommapp/static/images')),
            ],
        ),
        migrations.CreateModel(
            name='reg_buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('buyer_img', models.FileField(upload_to='ecommapp/static/images')),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='reg_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('img_name', models.FileField(upload_to='ecommapp/static/images')),
                ('phone', models.IntegerField()),
                ('cname', models.CharField(max_length=30)),
                ('com_details', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('man_name1', models.CharField(max_length=30)),
                ('med_name1', models.CharField(max_length=30)),
                ('dosage1', models.CharField(max_length=30)),
                ('type1', models.CharField(max_length=30)),
                ('qty1', models.IntegerField()),
                ('price1', models.IntegerField()),
                ('mtf1', models.CharField(max_length=30)),
                ('med_pic1', models.FileField(upload_to='')),
            ],
        ),
    ]
