# Generated by Django 4.2.5 on 2023-09-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('est_del_date', models.DateField(null=True)),
                ('products', models.CharField(max_length=200)),
                ('prod_img', models.FileField(upload_to='')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
