# Generated by Django 4.2.5 on 2023-09-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_final_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_deliver',
            name='username',
        ),
    ]
