# Generated by Django 4.2.5 on 2023-10-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_user_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_deliver',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_deliver',
            name='district',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_deliver',
            name='state',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_deliver',
            name='zip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
