# Generated by Django 4.2.5 on 2023-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0007_user_deliver_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_deliver',
            name='zip',
            field=models.CharField(max_length=30),
        ),
    ]
