# Generated by Django 4.2.5 on 2023-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_alter_user_deliver_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_deliver',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_deliver',
            name='qty',
            field=models.CharField(max_length=30),
        ),
    ]
