# Generated by Django 4.2.5 on 2023-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_alter_user_deliver_price_alter_user_deliver_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_buyer',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reg_seller',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
