# Generated by Django 4.2.5 on 2023-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0010_alter_reg_buyer_phone_alter_reg_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='type',
            field=models.CharField(choices=[('baby', 'baby'), ('health', 'health'), ('women', 'women'), ('personal', 'personal'), ('ayurveda', 'ayurveda'), ('healthd', 'healthd'), ('home', 'home'), ('healthc', 'healthc')], max_length=30),
        ),
    ]
